### ISSUE TITLE
Rails 7.2: Could not find table 'objects' (ActiveRecord::StatementInvalid)

### ISSUE THREAD

**Issue by timfsw** [makandra/active_type#190]
After updating to Rails 7.2, I now get the following error message:

> Could not find table 'objects'

Code: 

``` ruby
class SignInForm < ActiveType::Object
  attribute :username, :string
  attribute :password, :string

  validates :username, presence: true
  validates :password, presence: true
end
```

Stacktrace: 

```
[activerecord (7.2.0) lib/active_record/connection_adapters/sqlite3_adapter.rb:476:in `table_structure'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/abstract/schema_statements.rb:109:in `columns'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/schema_cache.rb:345:in `block (2 levels) in columns'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:407:in `with_connection'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/schema_cache.rb:344:in `block in columns'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/schema_cache.rb:343:in `fetch'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/schema_cache.rb:343:in `columns'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/schema_cache.rb:354:in `block in columns_hash'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/schema_cache.rb:353:in `fetch'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/schema_cache.rb:353:in `columns_hash'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/schema_cache.rb:54:in `columns_hash'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/schema_cache.rb:198:in `columns_hash'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/model_schema.rb:592:in `load_schema!'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/counter_cache.rb:187:in `load_schema!'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/model_schema.rb:539:in `block in load_schema'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/model_schema.rb:536:in `synchronize'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/model_schema.rb:536:in `load_schema'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/model_schema.rb:429:in `columns_hash'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/attributes.rb:243:in `block in _default_attributes'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:413:in `with_connection'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/connection_handling.rb:296:in `with_connection'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/attributes.rb:242:in `_default_attributes'](http://localhost:3000/#)
[activemodel (7.2.0) lib/active_model/attribute_registration.rb:38:in `attribute_types'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/attribute_methods.rb:260:in `_has_attribute?'](http://localhost:3000/#)
[activerecord (7.2.0) lib/active_record/inheritance.rb:61:in `new'](http://localhost:3000/#)
```

Versions:
- ruby: `3.3.3`
- rails: `7.2.0`
- active_type: `2.5.0`

**Comment by kratob** [comment]
Thanks for the report, I can reproduce this and will take a look.

**Comment by kratob** [comment]
I've just pushed version 2.5.1 which should have fixed this error.
I don't currently have a 7.2 project to do a bigger integration test, so I would not be too suprised if there a still other issues.
